### ISSUE TITLE
[Android] Demo project appyx-navigation does not works with minify enabled

### ISSUE THREAD

**Issue by arok** [bumble-tech/appyx#710]
Got the following crash on demo app start (and the same I have in my KMP project)

`java.lang.IllegalStateException: LifecycleOwner of this LifecycleRegistry is already garbage collected. It is too late to change lifecycle state.
                                                                                                        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.jvm.kt:282)
                                                                                                        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.jvm.kt:142)
                                                                                                        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.jvm.kt:107)
                                                                                                        at com.bumble.appyx.navigation.platform.PlatformLifecycleRegistry.setCurrentState(PlatformLifecycleRegistry.kt:31)
                                                                                                        at com.bumble.appyx.navigation.lifecycle.NodeLifecycleImpl.updateLifecycleState(NodeLifecycleImpl.kt:14)
                                                                                                        at com.bumble.appyx.navigation.node.Node.updateLifecycleState(Node.kt:173)
                                                                                                        at com.bumble.appyx.navigation.lifecycle.ChildNodeLifecycleManager.setState(ChildNodeLifecycleManager.kt:90)
                                                                                                        at com.bumble.appyx.navigation.lifecycle.ChildNodeLifecycleManager.access$setState(ChildNodeLifecycleManager.kt:19)
                                                                                                        at com.bumble.appyx.navigation.lifecycle.ChildNodeLifecycleManager$launch$1$4.emit(ChildNodeLifecycleManager.kt:64)
                                                                                                        at com.bumble.appyx.navigation.lifecycle.ChildNodeLifecycleManager$launch$1$4.emit(ChildNodeLifecycleManager.kt:61)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invokeSuspend(Zip.kt:258)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(Zip.kt)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(Zip.kt)
                                                                                                        at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:73)
                                                                                                        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
                                                                                                        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:241)
                                                                                                        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
                                                                                                        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466)
                                                                                                        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500)
                                                                                                        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489)
                                                                                                        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
                                                                                                        at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:286)
                                                                                                        at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:349)
                                                                                                        at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:316)
                                                                                                        at kotlinx.coroutines.flow.StateFlowImpl.emit(StateFlow.kt:373)
                                                                                                        at com.bumble.appyx.interactions.model.BaseAppyxComponent$observeVisualisation$1$3.emit(BaseAppyxComponent.kt:216)
                                                                                                        at com.bumble.appyx.interactions.model.BaseAppyxComponent$observeVisualisation$1$3.emit(BaseAppyxComponent.kt:213)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
                                                                                                        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                        at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                        at android.os.Looper.loop(Looper.java:223)
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by kabeer95** [comment]
@arok if its paid issue , i would love to contribute
